const productsHombreProducts = [
    {
      id: 1,
      name: "CAMISETA ESTAMPADO HI-FI",
      image1: "https://res.cloudinary.com/deabexp8e/image/upload/v1739791283/ITEK%20Front/ROPA%20HOMBRE/Camisetas/kj5g2lpvmdze0j2gmjvw.png",
      image2: "https://res.cloudinary.com/deabexp8e/image/upload/v1739791282/ITEK%20Front/ROPA%20HOMBRE/Camisetas/xndq99zbykgrolyyjssv.png",
      image3: "https://res.cloudinary.com/deabexp8e/image/upload/v1739791281/ITEK%20Front/ROPA%20HOMBRE/Camisetas/z8uvhwtdxuyzkq5pbv6j.png",
      showColorBox: false,
      price: 15.00,
      descripcion: "Camiseta relaxed fit. Cuello redondo y manga corta. Estampación combinada a contraste en espalda",
      referencia: "Blanco | 6210/400/200",
      composicion: "80% algodón",
      cuidados: "Los lavados a bajas temperaturas y los programas de centrifugado suaves son más delicados con las prendas, ayudando a mantener el color, la forma y la estructura del tejido. Al mismo tiempo, reduce el consumo de energía que se utiliza en los procesos de cuidado. ",
    },
    {
      id: 2,
      name: "CAMISETA ESTAMPADO TOSTADA LIMITED EDITION",
      image1: "https://res.cloudinary.com/deabexp8e/image/upload/v1739618284/ITEK%20Front/ROPA%20HOMBRE/Camisetas/ocg9b1qwnxizkb9qoxei.png",
      image2: "https://res.cloudinary.com/deabexp8e/image/upload/v1739618284/ITEK%20Front/ROPA%20HOMBRE/Camisetas/avigtfdkwku30okgxvtr.png",
      image3: "https://res.cloudinary.com/deabexp8e/image/upload/v1739618285/ITEK%20Front/ROPA%20HOMBRE/Camisetas/nzmsybn32olql8l7i9r2.png",
      showColorBox: false,
      price: 19.95,
      descripcion: "Camiseta relaxed fit. Cuello redondo y manga corta. Estampación combinada a contraste en espalda",
      referencia: "Blanco | 6224/407/250",
      composicion: "100% algodón",
      cuidados: "Los lavados a bajas temperaturas y los programas de centrifugado suaves son más delicados con las prendas, ayudando a mantener el color, la forma y la estructura del tejido. Al mismo tiempo, reduce el consumo de energía que se utiliza en los procesos de cuidado. ",
    },
    {
      id: 3,
      name: "CAMISETA RAYAS ROJA",
      image1: "https://res.cloudinary.com/deabexp8e/image/upload/v1740909616/ITEK%20Front/ROPA%20HOMBRE/Camisetas/gtzyueq8atmhqvfld2dp.jpg",
      image2: "https://res.cloudinary.com/deabexp8e/image/upload/v1740909619/ITEK%20Front/ROPA%20HOMBRE/Camisetas/p3ldtnq2tva0qtbrz5zm.jpg",
      image3: "https://res.cloudinary.com/deabexp8e/image/upload/v1740909628/ITEK%20Front/ROPA%20HOMBRE/Camisetas/qxngkbjzhssev4zvuuq2.jpg",
      showColorBox: false,
      color: "#9c5170",
      price: 11.95,
      descripcion: "Camiseta relaxed fit. Cuello redondo y manga corta. Estampación combinada a contraste en espalda",
      referencia: "Negro | 4224/2007/150",
      composicion: "100% algodón",
      cuidados: "Los lavados a bajas temperaturas y los programas de centrifugado suaves son más delicados con las prendas, ayudando a mantener el color, la forma y la estructura del tejido. Al mismo tiempo, reduce el consumo de energía que se utiliza en los procesos de cuidado. ",
      },
    {
      id: 4,
      name: "CAMISETA FOTOGRAFÍA @ RAFAEL MOURA",
      image1: "https://res.cloudinary.com/deabexp8e/image/upload/v1739823335/ITEK%20Front/ROPA%20HOMBRE/Camisetas/uu9mbtjoxlc9bu3o9kxv.jpg",
      image2: "https://res.cloudinary.com/deabexp8e/image/upload/v1739823354/ITEK%20Front/ROPA%20HOMBRE/Camisetas/hqsrtlknbpmwjxcbinsd.png",
      image3: "https://res.cloudinary.com/deabexp8e/image/upload/v1739823350/ITEK%20Front/ROPA%20HOMBRE/Camisetas/kslbsvwul6ubpbyybhdh.png",
      showColorBox: false,
      price: 25.45,
      descripcion: "Camiseta regular fit. Cuello redondo y manga corta. Estampado fotográfico de @Rafael Moura combinado a contraste en delantero.",
      referencia: "Gris perla | 0679/314/804",
      composicion: "100% algodón",
      cuidados: "Los lavados a bajas temperaturas y los programas de centrifugado suaves son más delicados con las prendas, ayudando a mantener el color, la forma y la estructura del tejido. Al mismo tiempo, reduce el consumo de energía que se utiliza en los procesos de cuidado. ",
     },
     {
      id: 5,
      name: "SUDADERA GRIS",
      image1: "https://res.cloudinary.com/deabexp8e/image/upload/v1740909630/ITEK%20Front/ROPA%20HOMBRE/Camisetas/wdgiaeovf2j4qxqfpfci.jpg",
      image2: "https://res.cloudinary.com/deabexp8e/image/upload/v1740909631/ITEK%20Front/ROPA%20HOMBRE/Camisetas/yoosycecz06ofysghorf.jpg",
      image3: "https://res.cloudinary.com/deabexp8e/image/upload/v1740909634/ITEK%20Front/ROPA%20HOMBRE/Camisetas/bwjbtoa3wpb0uzyome97.jpg",
      showColorBox: true,
      color: "#9c5170",
      price: 11.95,
      descripcion: "Camiseta relaxed fit. Cuello redondo y manga corta. Estampación combinada a contraste en espalda",
      referencia: "Negro | 4224/2007/150",
      composicion: "100% algodón",
      cuidados: "Los lavados a bajas temperaturas y los programas de centrifugado suaves son más delicados con las prendas, ayudando a mantener el color, la forma y la estructura del tejido. Al mismo tiempo, reduce el consumo de energía que se utiliza en los procesos de cuidado. ",
      },
    {
      id: 6,
      name: "JERSEY AZUL ESTAMPADO",
      image1: "https://res.cloudinary.com/deabexp8e/image/upload/v1740909635/ITEK%20Front/ROPA%20HOMBRE/Camisetas/uzyg4rmmnf5udcddmrq6.jpg",
      image2: "https://res.cloudinary.com/deabexp8e/image/upload/v1740909637/ITEK%20Front/ROPA%20HOMBRE/Camisetas/pga8bmatg4zmzitt5jis.jpg",
      image3: "https://res.cloudinary.com/deabexp8e/image/upload/v1740909638/ITEK%20Front/ROPA%20HOMBRE/Camisetas/jpwbfkk3lynygl4pwyf4.jpg",
      showColorBox: false,
      price: 25.45,
      descripcion: "Camiseta regular fit. Cuello redondo y manga corta. Estampado fotográfico de @Rafael Moura combinado a contraste en delantero.",
      referencia: "Gris perla | 0679/314/804",
      composicion: "100% algodón",
      cuidados: "Los lavados a bajas temperaturas y los programas de centrifugado suaves son más delicados con las prendas, ayudando a mantener el color, la forma y la estructura del tejido. Al mismo tiempo, reduce el consumo de energía que se utiliza en los procesos de cuidado. ",
     },
  
  ];

// id hasta 32  van a ser 4 productos de cada molde

  export default productsHombreProducts;