const HogarProducts =  [
    {
        id: 97,
        name: "HEMNES",
        image1: "https://res.cloudinary.com/deabexp8e/image/upload/v1739871564/ITEK%20Front/HOME/SALON/mueble%20tv/wbwggayevxnzvagr7mso.avif",
        image2: "https://res.cloudinary.com/deabexp8e/image/upload/v1739871563/ITEK%20Front/HOME/SALON/mueble%20tv/xkrjqtyinyzxcsowxgiy.webp",
        image3: "https://res.cloudinary.com/deabexp8e/image/upload/v1739871562/ITEK%20Front/HOME/SALON/mueble%20tv/subgjavvlmgk9m6lt9cp.avif",
        showColorBox: false,
        price: 189,
        descripcion: "Mueble TV, tinte blanco/marrón claro, 148x47x57 cm",
        referencia: "504.135.26",
        composicion: "La madera maciza tiene un aspecto natural.",
        cuidados: "Un mueble bonito hecho con madera maciza de pino obtenida de fuentes sostenibles, un material renovable cuyo aspecto mejora con el paso del tiempo. Si te gusta, combínalo con otros productos de la serie HEMNES",
      },
      {
        id: 98,
        name: "FJÄLLBO",
        image1: "https://res.cloudinary.com/deabexp8e/image/upload/v1739875346/ITEK%20Front/HOME/SALON/mueble%20tv/gbitjpwlbd6svtngh7ij.avif",
        image2: "https://res.cloudinary.com/deabexp8e/image/upload/v1739875349/ITEK%20Front/HOME/SALON/mueble%20tv/ugn9to3d60daqconnwbg.avif",
        image3: "https://res.cloudinary.com/deabexp8e/image/upload/v1739875348/ITEK%20Front/HOME/SALON/mueble%20tv/vtobhril6kmelxowwhfv.avif",
        showColorBox: false,
        price: 119,
        descripcion: "Mueble TV, negro, 150x36x54 cm",
        referencia: "903.392.90",
        composicion: "Acero, Resina epoxi/revestimiento de poliéster en polvo",
        cuidados: "Las puertas de la serie FJÄLLBO permiten el paso de las señales del mando a distancia, así que tus equipos electrónicos estarán encantados. Probablemente tú también: la parte trasera abierta facilita la gestión de los cables.",
    },
    {
        id: 99,
        name: "FRYKSÅS",
        image1: "https://res.cloudinary.com/deabexp8e/image/upload/v1739876082/ITEK%20Front/HOME/SALON/mueble%20tv/qbslfehbrj3v5di57m1z.avif",
        image2: "https://res.cloudinary.com/deabexp8e/image/upload/v1739876081/ITEK%20Front/HOME/SALON/mueble%20tv/ahuc8qqfe28yxk4pkp08.avif",
        image3: "https://res.cloudinary.com/deabexp8e/image/upload/v1739876079/ITEK%20Front/HOME/SALON/mueble%20tv/pjthejoqpmyqhy5sw5e2.avif",
        showColorBox: false,
        price: 299,
        descripcion: "Mueble TV, tinte blanco/marrón claro, 148x47x57 cm",
        referencia: "504.135.26",
        composicion: "La madera maciza tiene un aspecto natural.",
        cuidados: "Un mueble bonito hecho con madera maciza de pino obtenida de fuentes sostenibles, un material renovable cuyo aspecto mejora con el paso del tiempo. Si te gusta, combínalo con otros productos de la serie HEMNES",
      },
      {
        id: 100,
        name: "SKRUVBY",
        image1: "https://res.cloudinary.com/deabexp8e/image/upload/v1739876154/ITEK%20Front/HOME/SALON/mueble%20tv/ls8f11q9hxypjia445hr.avif",
        image2: "https://res.cloudinary.com/deabexp8e/image/upload/v1739876155/ITEK%20Front/HOME/SALON/mueble%20tv/xcxpr1tz49w97se0sj9p.avif",
        image3: "https://res.cloudinary.com/deabexp8e/image/upload/v1739876153/ITEK%20Front/HOME/SALON/mueble%20tv/zbyd2cc9sd6bmdextibx.avif",
        showColorBox: false,
        price: 99.99,
        descripcion: "Mueble TV, negro, 150x36x54 cm",
        referencia: "903.392.90",
        composicion: "Acero, Resina epoxi/revestimiento de poliéster en polvo",
        cuidados: "Las puertas de la serie FJÄLLBO permiten el paso de las señales del mando a distancia, así que tus equipos electrónicos estarán encantados. Probablemente tú también: la parte trasera abierta facilita la gestión de los cables.",
   
          },
    {
      id: 101,
      name: "Sofa BolaK",
      image1: "https://res.cloudinary.com/deabexp8e/image/upload/v1738682139/ITEK%20Front/HOME/SALON/Sofa%201/p6jjgnn9ljqjs2fvp5jr.png",
      image2: "https://res.cloudinary.com/deabexp8e/image/upload/v1738682139/ITEK%20Front/HOME/SALON/Sofa%201/alaz65tdu1doksi2ps2d.png",
      image3: "https://res.cloudinary.com/deabexp8e/image/upload/v1738682139/ITEK%20Front/HOME/SALON/Sofa%201/jpqixcngg1dcogbymwm2.png",
      showColorBox: false,
      price: 199.99,
      descripcion: "Sofa de salon largo",
      referencia: "903.3eq2.90",
      composicion: "Pelo y tela",
      cuidados: "Las puertas de la serie FJÄLLBO permiten el paso de las señales del mando a distancia, así que tus equipos electrónicos estarán encantados. Probablemente tú también: la parte trasera abierta facilita la gestión de los cables.",
 },
    {
      id: 102,
      name: "Sofa Uni",
      image1: "https://res.cloudinary.com/deabexp8e/image/upload/v1738682216/ITEK%20Front/HOME/SALON/Sofa%203/ihcbkmki3ajghibyiboc.png",
      image2: "https://res.cloudinary.com/deabexp8e/image/upload/v1738682215/ITEK%20Front/HOME/SALON/Sofa%203/fzysj9eyliznlqprarlx.png",
      image3: "https://res.cloudinary.com/deabexp8e/image/upload/v1738682205/ITEK%20Front/HOME/SALON/Sofa%203/sdplvmhd3v9zpfnqmfrv.png",
      showColorBox: false,
      price: 119,
      descripcion: "Mueble TV, negro, 150x36x54 cm",
      referencia: "903.392.90",
      composicion: "Acero, Resina epoxi/revestimiento de poliéster en polvo",
      cuidados: "Las puertas de la serie FJÄLLBO permiten el paso de las señales del mando a distancia, así que tus equipos electrónicos estarán encantados. Probablemente tú también: la parte trasera abierta facilita la gestión de los cables.",
  },
  {
      id: 103,
      name: "FRYKSÅS",
      image1: "https://res.cloudinary.com/deabexp8e/image/upload/v1739876082/ITEK%20Front/HOME/SALON/mueble%20tv/qbslfehbrj3v5di57m1z.avif",
      image2: "https://res.cloudinary.com/deabexp8e/image/upload/v1739876081/ITEK%20Front/HOME/SALON/mueble%20tv/ahuc8qqfe28yxk4pkp08.avif",
      image3: "https://res.cloudinary.com/deabexp8e/image/upload/v1739876079/ITEK%20Front/HOME/SALON/mueble%20tv/pjthejoqpmyqhy5sw5e2.avif",
      showColorBox: false,
      price: 299,
      descripcion: "Mueble TV, tinte blanco/marrón claro, 148x47x57 cm",
      referencia: "504.135.26",
      composicion: "La madera maciza tiene un aspecto natural.",
      cuidados: "Un mueble bonito hecho con madera maciza de pino obtenida de fuentes sostenibles, un material renovable cuyo aspecto mejora con el paso del tiempo. Si te gusta, combínalo con otros productos de la serie HEMNES",
    },
    {
      id: 104,
      name: "SKRUVBY",
      image1: "https://res.cloudinary.com/deabexp8e/image/upload/v1739876154/ITEK%20Front/HOME/SALON/mueble%20tv/ls8f11q9hxypjia445hr.avif",
      image2: "https://res.cloudinary.com/deabexp8e/image/upload/v1739876155/ITEK%20Front/HOME/SALON/mueble%20tv/xcxpr1tz49w97se0sj9p.avif",
      image3: "https://res.cloudinary.com/deabexp8e/image/upload/v1739876153/ITEK%20Front/HOME/SALON/mueble%20tv/zbyd2cc9sd6bmdextibx.avif",
      showColorBox: false,
      price: 99.99,
      descripcion: "Mueble TV, negro, 150x36x54 cm",
      referencia: "903.392.90",
      composicion: "Acero, Resina epoxi/revestimiento de poliéster en polvo",
      cuidados: "Las puertas de la serie FJÄLLBO permiten el paso de las señales del mando a distancia, así que tus equipos electrónicos estarán encantados. Probablemente tú también: la parte trasera abierta facilita la gestión de los cables.",
  },
]
   
export default HogarProducts;