const RopaMujerProduct = [
    {
        id: 33,
        name: "VESTIDO AMARILLO",
        image1: "https://res.cloudinary.com/deabexp8e/image/upload/v1740910206/ITEK%20Front/ROPA%20MUJER/Vestidos/d3jgwd1byxgqzzz87s4l.jpg",
        image2: "https://res.cloudinary.com/deabexp8e/image/upload/v1740910209/ITEK%20Front/ROPA%20MUJER/Vestidos/iduxiquel9lnvcz3vnpt.jpg",
        image3: "https://res.cloudinary.com/deabexp8e/image/upload/v1740910210/ITEK%20Front/ROPA%20MUJER/Vestidos/epmcwrfstpnbjtsashc4.jpg",
        showColorBox: true,
        color: "#FFFF00",
        price: 45.00,
        descripcion: "Camiseta relaxed fit. Cuello redondo y manga corta. Estampación combinada a contraste en espalda",
        referencia: "Blanco | 6210/400/200",
        composicion: "80% algodón",
        cuidados: "Los lavados a bajas temperaturas y los programas de centrifugado suaves son más delicados con las prendas, ayudando a mantener el color, la forma y la estructura del tejido. Al mismo tiempo, reduce el consumo de energía que se utiliza en los procesos de cuidado. ",
      },
      {
        id: 34,
      name: "VESTIDO CON FALDA DE TUL",
        image1: "https://res.cloudinary.com/deabexp8e/image/upload/v1740910212/ITEK%20Front/ROPA%20MUJER/Vestidos/cmtfc142dmbtnl6gxygi.jpg",
        image2: "https://res.cloudinary.com/deabexp8e/image/upload/v1740910213/ITEK%20Front/ROPA%20MUJER/Vestidos/ixdpwmy1csxt0ynxxxfa.jpg",
        image3: "https://res.cloudinary.com/deabexp8e/image/upload/v1740910214/ITEK%20Front/ROPA%20MUJER/Vestidos/jxmayusanhsygf2yxbmn.jpg",
        showColorBox: false,
        price: 19.95,
        descripcion: "Camiseta relaxed fit. Cuello redondo y manga corta. Estampación combinada a contraste en espalda",
        referencia: "Blanco | 6224/407/250",
        composicion: "100% algodón",
        cuidados: "Los lavados a bajas temperaturas y los programas de centrifugado suaves son más delicados con las prendas, ayudando a mantener el color, la forma y la estructura del tejido. Al mismo tiempo, reduce el consumo de energía que se utiliza en los procesos de cuidado. ",
      },
      {
        id: 35,
        name: "VESTIDO TIRANTES AZUL BRILLANTE",
        image1: "https://res.cloudinary.com/deabexp8e/image/upload/v1740910215/ITEK%20Front/ROPA%20MUJER/Vestidos/x4ecqoi79slaaxwueyxb.jpg",
        image2: "https://res.cloudinary.com/deabexp8e/image/upload/v1740910217/ITEK%20Front/ROPA%20MUJER/Vestidos/azfvu6c5txbqsxh0xpol.jpg",
        image3: "https://res.cloudinary.com/deabexp8e/image/upload/v1740910217/ITEK%20Front/ROPA%20MUJER/Vestidos/azfvu6c5txbqsxh0xpol.jpg",
        showColorBox: false,
        
        price: 11.95,
        descripcion: "Camiseta relaxed fit. Cuello redondo y manga corta. Estampación combinada a contraste en espalda",
        referencia: "Negro | 4224/2007/150",
        composicion: "100% algodón",
        cuidados: "Los lavados a bajas temperaturas y los programas de centrifugado suaves son más delicados con las prendas, ayudando a mantener el color, la forma y la estructura del tejido. Al mismo tiempo, reduce el consumo de energía que se utiliza en los procesos de cuidado. ",
        },
      {
        id: 36,
        name: "VESTIDO ESCOTADO AMARRILLO CLARO",
        image1: "https://res.cloudinary.com/deabexp8e/image/upload/v1740910219/ITEK%20Front/ROPA%20MUJER/Vestidos/mi5z3ykp0rye7ibztcp8.jpg",
        image2: "https://res.cloudinary.com/deabexp8e/image/upload/v1740910220/ITEK%20Front/ROPA%20MUJER/Vestidos/lvi91xbuifc6hypkexsd.jpg",
        image3: "https://res.cloudinary.com/deabexp8e/image/upload/v1740910221/ITEK%20Front/ROPA%20MUJER/Vestidos/zbkd13fsw7kgvwar1kxq.jpg",
        showColorBox: true,
        color: "#FF0000",
        price: 25.45,
        descripcion: "Camiseta regular fit. Cuello redondo y manga corta. Estampado fotográfico de @Rafael Moura combinado a contraste en delantero.",
        referencia: "Gris perla | 0679/314/804",
        composicion: "100% algodón",
        cuidados: "Los lavados a bajas temperaturas y los programas de centrifugado suaves son más delicados con las prendas, ayudando a mantener el color, la forma y la estructura del tejido. Al mismo tiempo, reduce el consumo de energía que se utiliza en los procesos de cuidado. ",
       },
    
]


export default RopaMujerProduct;