-- Insertar un usuario
-- Insertar usuarios adicionales
INSERT INTO users (username, email, password, direccion, telefono, rol, fechaRegistro) VALUES 
('Iago Vila', 'iagovila17@gmail.com', '$2a$10$OLFtHR1GqCSvZYtMHU2gv.9SYrBvlc6gKYD4eIZsPlPGenKzs9CNi', 'Rua Boa Vista', '607048861', 'ADMIN', NOW()),
('Iago Vila', 'iagovila18@gmail.com', '$2a$10$OLFtHR1GqCSvZYtMHU2gv.9SYrBvlc6gKYD4eIZsPlPGenKzs9CNi', 'Calle Falsa 123', '123456789', 'USER', NOW());


-- Insertar un producto enlazado con la categoría
INSERT INTO products (nombre, familia, referencia, composicion, descripcion, cuidados, precio, stock, imagen, imagen2, imagen3, color, categoria)
VALUES 
('ZW COLLECTION FAUX FUR JACKET' , 'chaqueta' ,'4360/246/832','100% polyester' ,'Caring for your clothes is caring for the environment.
To keep your jackets and coats clean, you only need to freshen them up and go over them with a cloth or a clothes brush. If you need to dry clean a garment, look for a dry cleaner that uses technologies that are respectful of the environment. ' ,'Long sleeve jacket with a lapel collar. Front pockets. Matching lining. Hidden button-up front.', 89.95, 150, 'https://res.cloudinary.com/deabexp8e/image/upload/v1746088625/ITEK%20Front/ROPA%20MUJER/Chaquetas/kebbb6mwy0thr46u2yni.jpg', 'https://res.cloudinary.com/deabexp8e/image/upload/v1746088630/ITEK%20Front/ROPA%20MUJER/Chaquetas/ad5wjldcyfhc0rrftcna.jpg', 'https://res.cloudinary.com/deabexp8e/image/upload/v1746088633/ITEK%20Front/ROPA%20MUJER/Chaquetas/oqamzck4g7fehwgj5cnk.jpg', 'Taupe grey', "mujer"),
( 'PANTALÓN RELAXED FIT ALGODÓN - lino' , 'lino' ,'1437/450/800','100% lino' ,'Los lavados a baja temperatura y los centrifugados delicados son más suaves con las prendas y ayudan a proteger el color, la forma y la estructura del tejido. Además, reducen la cantidad de energía utilizada en los procesos de cuidado.' , 'Pantalón relaxed fit confeccionado en tejido con mezcla de algodón y 14% de lino. Cintura elástica ajustable con cordón. Bolsillos frontales y detalle de bolsillos traseros.', 29.95, 1200, 'https://res.cloudinary.com/deabexp8e/image/upload/v1746101881/ITEK%20Front/ROPA%20HOMBRE/lino/l3tdiuop20xmygs8nmdf.jpg', 'https://res.cloudinary.com/deabexp8e/image/upload/v1746101883/ITEK%20Front/ROPA%20HOMBRE/lino/cm1zehizjy0mbageud79.jpg', 'https://res.cloudinary.com/deabexp8e/image/upload/v1746101884/ITEK%20Front/ROPA%20HOMBRE/lino/hbstvfwuu6ecarwzptyl.jpg', 'Negro', "hombre"),
( 'PANTALÓN RELAXED FIT ALGODÓN - lino' , 'lino' ,'1437/450/800','100% lino' ,'Los lavados a baja temperatura y los centrifugados delicados son más suaves con las prendas y ayudan a proteger el color, la forma y la estructura del tejido. Además, reducen la cantidad de energía utilizada en los procesos de cuidado.' , 'Pantalón relaxed fit confeccionado en tejido con mezcla de algodón y 14% de lino. Cintura elástica ajustable con cordón. Bolsillos frontales y detalle de bolsillos traseros.', 29.95, 1200, 'https://res.cloudinary.com/deabexp8e/image/upload/v1746101881/ITEK%20Front/ROPA%20HOMBRE/lino/l3tdiuop20xmygs8nmdf.jpg', 'https://res.cloudinary.com/deabexp8e/image/upload/v1746101883/ITEK%20Front/ROPA%20HOMBRE/lino/cm1zehizjy0mbageud79.jpg', 'https://res.cloudinary.com/deabexp8e/image/upload/v1746101884/ITEK%20Front/ROPA%20HOMBRE/lino/hbstvfwuu6ecarwzptyl.jpg', 'Negro', "hombre"),
( 'PANTALÓN RELAXED FIT ALGODÓN - lino' , 'lino' ,'1437/450/800','100% lino' ,'Los lavados a baja temperatura y los centrifugados delicados son más suaves con las prendas y ayudan a proteger el color, la forma y la estructura del tejido. Además, reducen la cantidad de energía utilizada en los procesos de cuidado.' , 'Pantalón relaxed fit confeccionado en tejido con mezcla de algodón y 14% de lino. Cintura elástica ajustable con cordón. Bolsillos frontales y detalle de bolsillos traseros.', 29.95, 1200, 'https://res.cloudinary.com/deabexp8e/image/upload/v1746101881/ITEK%20Front/ROPA%20HOMBRE/lino/l3tdiuop20xmygs8nmdf.jpg', 'https://res.cloudinary.com/deabexp8e/image/upload/v1746101883/ITEK%20Front/ROPA%20HOMBRE/lino/cm1zehizjy0mbageud79.jpg', 'https://res.cloudinary.com/deabexp8e/image/upload/v1746101884/ITEK%20Front/ROPA%20HOMBRE/lino/hbstvfwuu6ecarwzptyl.jpg', 'Negro', "hombre"),
( 'PANTALÓN RELAXED FIT ALGODÓN - lino' , 'lino' ,'1437/450/800','100% lino' ,'Los lavados a baja temperatura y los centrifugados delicados son más suaves con las prendas y ayudan a proteger el color, la forma y la estructura del tejido. Además, reducen la cantidad de energía utilizada en los procesos de cuidado.' , 'Pantalón relaxed fit confeccionado en tejido con mezcla de algodón y 14% de lino. Cintura elástica ajustable con cordón. Bolsillos frontales y detalle de bolsillos traseros.', 29.95, 1200, 'https://res.cloudinary.com/deabexp8e/image/upload/v1746101881/ITEK%20Front/ROPA%20HOMBRE/lino/l3tdiuop20xmygs8nmdf.jpg', 'https://res.cloudinary.com/deabexp8e/image/upload/v1746101883/ITEK%20Front/ROPA%20HOMBRE/lino/cm1zehizjy0mbageud79.jpg', 'https://res.cloudinary.com/deabexp8e/image/upload/v1746101884/ITEK%20Front/ROPA%20HOMBRE/lino/hbstvfwuu6ecarwzptyl.jpg', 'Negro', "hombre"),
( 'PANTALÓN RELAXED FIT ALGODÓN - lino' , 'lino' ,'1437/450/800','100% lino' ,'Los lavados a baja temperatura y los centrifugados delicados son más suaves con las prendas y ayudan a proteger el color, la forma y la estructura del tejido. Además, reducen la cantidad de energía utilizada en los procesos de cuidado.' , 'Pantalón relaxed fit confeccionado en tejido con mezcla de algodón y 14% de lino. Cintura elástica ajustable con cordón. Bolsillos frontales y detalle de bolsillos traseros.', 29.95, 1200, 'https://res.cloudinary.com/deabexp8e/image/upload/v1746101881/ITEK%20Front/ROPA%20HOMBRE/lino/l3tdiuop20xmygs8nmdf.jpg', 'https://res.cloudinary.com/deabexp8e/image/upload/v1746101883/ITEK%20Front/ROPA%20HOMBRE/lino/cm1zehizjy0mbageud79.jpg', 'https://res.cloudinary.com/deabexp8e/image/upload/v1746101884/ITEK%20Front/ROPA%20HOMBRE/lino/hbstvfwuu6ecarwzptyl.jpg', 'Negro', "hombre"),
( 'PANTALÓN RELAXED FIT ALGODÓN - lino' , 'lino' ,'1437/450/800','100% lino' ,'Los lavados a baja temperatura y los centrifugados delicados son más suaves con las prendas y ayudan a proteger el color, la forma y la estructura del tejido. Además, reducen la cantidad de energía utilizada en los procesos de cuidado.' , 'Pantalón relaxed fit confeccionado en tejido con mezcla de algodón y 14% de lino. Cintura elástica ajustable con cordón. Bolsillos frontales y detalle de bolsillos traseros.', 29.95, 1200, 'https://res.cloudinary.com/deabexp8e/image/upload/v1746101881/ITEK%20Front/ROPA%20HOMBRE/lino/l3tdiuop20xmygs8nmdf.jpg', 'https://res.cloudinary.com/deabexp8e/image/upload/v1746101883/ITEK%20Front/ROPA%20HOMBRE/lino/cm1zehizjy0mbageud79.jpg', 'https://res.cloudinary.com/deabexp8e/image/upload/v1746101884/ITEK%20Front/ROPA%20HOMBRE/lino/hbstvfwuu6ecarwzptyl.jpg', 'Negro', "hombre"),
( 'PANTALÓN RELAXED FIT ALGODÓN - lino' , 'lino' ,'1437/450/800','100% lino' ,'Los lavados a baja temperatura y los centrifugados delicados son más suaves con las prendas y ayudan a proteger el color, la forma y la estructura del tejido. Además, reducen la cantidad de energía utilizada en los procesos de cuidado.' , 'Pantalón relaxed fit confeccionado en tejido con mezcla de algodón y 14% de lino. Cintura elástica ajustable con cordón. Bolsillos frontales y detalle de bolsillos traseros.', 29.95, 1200, 'https://res.cloudinary.com/deabexp8e/image/upload/v1746101881/ITEK%20Front/ROPA%20HOMBRE/lino/l3tdiuop20xmygs8nmdf.jpg', 'https://res.cloudinary.com/deabexp8e/image/upload/v1746101883/ITEK%20Front/ROPA%20HOMBRE/lino/cm1zehizjy0mbageud79.jpg', 'https://res.cloudinary.com/deabexp8e/image/upload/v1746101884/ITEK%20Front/ROPA%20HOMBRE/lino/hbstvfwuu6ecarwzptyl.jpg', 'Negro', "hombre"),
( 'PANTALÓN RELAXED FIT ALGODÓN - lino' , 'lino' ,'1437/450/800','100% lino' ,'Los lavados a baja temperatura y los centrifugados delicados son más suaves con las prendas y ayudan a proteger el color, la forma y la estructura del tejido. Además, reducen la cantidad de energía utilizada en los procesos de cuidado.' , 'Pantalón relaxed fit confeccionado en tejido con mezcla de algodón y 14% de lino. Cintura elástica ajustable con cordón. Bolsillos frontales y detalle de bolsillos traseros.', 29.95, 1200, 'https://res.cloudinary.com/deabexp8e/image/upload/v1746101881/ITEK%20Front/ROPA%20HOMBRE/lino/l3tdiuop20xmygs8nmdf.jpg', 'https://res.cloudinary.com/deabexp8e/image/upload/v1746101883/ITEK%20Front/ROPA%20HOMBRE/lino/cm1zehizjy0mbageud79.jpg', 'https://res.cloudinary.com/deabexp8e/image/upload/v1746101884/ITEK%20Front/ROPA%20HOMBRE/lino/hbstvfwuu6ecarwzptyl.jpg', 'Negro', "hombre"),
( 'PANTALÓN RELAXED FIT ALGODÓN - lino' , 'lino' ,'1437/450/800','100% lino' ,'Los lavados a baja temperatura y los centrifugados delicados son más suaves con las prendas y ayudan a proteger el color, la forma y la estructura del tejido. Además, reducen la cantidad de energía utilizada en los procesos de cuidado.' , 'Pantalón relaxed fit confeccionado en tejido con mezcla de algodón y 14% de lino. Cintura elástica ajustable con cordón. Bolsillos frontales y detalle de bolsillos traseros.', 29.95, 1200, 'https://res.cloudinary.com/deabexp8e/image/upload/v1746101881/ITEK%20Front/ROPA%20HOMBRE/lino/l3tdiuop20xmygs8nmdf.jpg', 'https://res.cloudinary.com/deabexp8e/image/upload/v1746101883/ITEK%20Front/ROPA%20HOMBRE/lino/cm1zehizjy0mbageud79.jpg', 'https://res.cloudinary.com/deabexp8e/image/upload/v1746101884/ITEK%20Front/ROPA%20HOMBRE/lino/hbstvfwuu6ecarwzptyl.jpg', 'Negro', "hombre"),
( 'PANTALÓN RELAXED FIT ALGODÓN - lino' , 'lino' ,'1437/450/800','100% lino' ,'Los lavados a baja temperatura y los centrifugados delicados son más suaves con las prendas y ayudan a proteger el color, la forma y la estructura del tejido. Además, reducen la cantidad de energía utilizada en los procesos de cuidado.' , 'Pantalón relaxed fit confeccionado en tejido con mezcla de algodón y 14% de lino. Cintura elástica ajustable con cordón. Bolsillos frontales y detalle de bolsillos traseros.', 29.95, 1200, 'https://res.cloudinary.com/deabexp8e/image/upload/v1746101881/ITEK%20Front/ROPA%20HOMBRE/lino/l3tdiuop20xmygs8nmdf.jpg', 'https://res.cloudinary.com/deabexp8e/image/upload/v1746101883/ITEK%20Front/ROPA%20HOMBRE/lino/cm1zehizjy0mbageud79.jpg', 'https://res.cloudinary.com/deabexp8e/image/upload/v1746101884/ITEK%20Front/ROPA%20HOMBRE/lino/hbstvfwuu6ecarwzptyl.jpg', 'Negro', "hombre"),
( 'PANTALÓN RELAXED FIT ALGODÓN - lino' , 'lino' ,'1437/450/800','100% lino' ,'Los lavados a baja temperatura y los centrifugados delicados son más suaves con las prendas y ayudan a proteger el color, la forma y la estructura del tejido. Además, reducen la cantidad de energía utilizada en los procesos de cuidado.' , 'Pantalón relaxed fit confeccionado en tejido con mezcla de algodón y 14% de lino. Cintura elástica ajustable con cordón. Bolsillos frontales y detalle de bolsillos traseros.', 29.95, 1200, 'https://res.cloudinary.com/deabexp8e/image/upload/v1746101881/ITEK%20Front/ROPA%20HOMBRE/lino/l3tdiuop20xmygs8nmdf.jpg', 'https://res.cloudinary.com/deabexp8e/image/upload/v1746101883/ITEK%20Front/ROPA%20HOMBRE/lino/cm1zehizjy0mbageud79.jpg', 'https://res.cloudinary.com/deabexp8e/image/upload/v1746101884/ITEK%20Front/ROPA%20HOMBRE/lino/hbstvfwuu6ecarwzptyl.jpg', 'Negro', "hombre"),
( 'PANTALÓN RELAXED FIT ALGODÓN - lino' , 'lino' ,'1437/450/800','100% lino' ,'Los lavados a baja temperatura y los centrifugados delicados son más suaves con las prendas y ayudan a proteger el color, la forma y la estructura del tejido. Además, reducen la cantidad de energía utilizada en los procesos de cuidado.' , 'Pantalón relaxed fit confeccionado en tejido con mezcla de algodón y 14% de lino. Cintura elástica ajustable con cordón. Bolsillos frontales y detalle de bolsillos traseros.', 29.95, 1200, 'https://res.cloudinary.com/deabexp8e/image/upload/v1746101881/ITEK%20Front/ROPA%20HOMBRE/lino/l3tdiuop20xmygs8nmdf.jpg', 'https://res.cloudinary.com/deabexp8e/image/upload/v1746101883/ITEK%20Front/ROPA%20HOMBRE/lino/cm1zehizjy0mbageud79.jpg', 'https://res.cloudinary.com/deabexp8e/image/upload/v1746101884/ITEK%20Front/ROPA%20HOMBRE/lino/hbstvfwuu6ecarwzptyl.jpg', 'Negro', "hombre"),
( 'PANTALÓN RELAXED FIT ALGODÓN - lino' , 'lino' ,'1437/450/800','100% lino' ,'Los lavados a baja temperatura y los centrifugados delicados son más suaves con las prendas y ayudan a proteger el color, la forma y la estructura del tejido. Además, reducen la cantidad de energía utilizada en los procesos de cuidado.' , 'Pantalón relaxed fit confeccionado en tejido con mezcla de algodón y 14% de lino. Cintura elástica ajustable con cordón. Bolsillos frontales y detalle de bolsillos traseros.', 29.95, 1200, 'https://res.cloudinary.com/deabexp8e/image/upload/v1746101881/ITEK%20Front/ROPA%20HOMBRE/lino/l3tdiuop20xmygs8nmdf.jpg', 'https://res.cloudinary.com/deabexp8e/image/upload/v1746101883/ITEK%20Front/ROPA%20HOMBRE/lino/cm1zehizjy0mbageud79.jpg', 'https://res.cloudinary.com/deabexp8e/image/upload/v1746101884/ITEK%20Front/ROPA%20HOMBRE/lino/hbstvfwuu6ecarwzptyl.jpg', 'Negro', "hombre"),
( 'PANTALÓN RELAXED FIT ALGODÓN - lino' , 'lino' ,'1437/450/800','100% lino' ,'Los lavados a baja temperatura y los centrifugados delicados son más suaves con las prendas y ayudan a proteger el color, la forma y la estructura del tejido. Además, reducen la cantidad de energía utilizada en los procesos de cuidado.' , 'Pantalón relaxed fit confeccionado en tejido con mezcla de algodón y 14% de lino. Cintura elástica ajustable con cordón. Bolsillos frontales y detalle de bolsillos traseros.', 29.95, 1200, 'https://res.cloudinary.com/deabexp8e/image/upload/v1746101881/ITEK%20Front/ROPA%20HOMBRE/lino/l3tdiuop20xmygs8nmdf.jpg', 'https://res.cloudinary.com/deabexp8e/image/upload/v1746101883/ITEK%20Front/ROPA%20HOMBRE/lino/cm1zehizjy0mbageud79.jpg', 'https://res.cloudinary.com/deabexp8e/image/upload/v1746101884/ITEK%20Front/ROPA%20HOMBRE/lino/hbstvfwuu6ecarwzptyl.jpg', 'Negro', "hombre"),
( 'PANTALÓN RELAXED FIT ALGODÓN - lino' , 'lino' ,'1437/450/800','100% lino' ,'Los lavados a baja temperatura y los centrifugados delicados son más suaves con las prendas y ayudan a proteger el color, la forma y la estructura del tejido. Además, reducen la cantidad de energía utilizada en los procesos de cuidado.' , 'Pantalón relaxed fit confeccionado en tejido con mezcla de algodón y 14% de lino. Cintura elástica ajustable con cordón. Bolsillos frontales y detalle de bolsillos traseros.', 29.95, 1200, 'https://res.cloudinary.com/deabexp8e/image/upload/v1746101881/ITEK%20Front/ROPA%20HOMBRE/lino/l3tdiuop20xmygs8nmdf.jpg', 'https://res.cloudinary.com/deabexp8e/image/upload/v1746101883/ITEK%20Front/ROPA%20HOMBRE/lino/cm1zehizjy0mbageud79.jpg', 'https://res.cloudinary.com/deabexp8e/image/upload/v1746101884/ITEK%20Front/ROPA%20HOMBRE/lino/hbstvfwuu6ecarwzptyl.jpg', 'Negro', "hombre"),
( 'PANTALÓN RELAXED FIT ALGODÓN - lino' , 'lino' ,'1437/450/800','100% lino' ,'Los lavados a baja temperatura y los centrifugados delicados son más suaves con las prendas y ayudan a proteger el color, la forma y la estructura del tejido. Además, reducen la cantidad de energía utilizada en los procesos de cuidado.' , 'Pantalón relaxed fit confeccionado en tejido con mezcla de algodón y 14% de lino. Cintura elástica ajustable con cordón. Bolsillos frontales y detalle de bolsillos traseros.', 29.95, 1200, 'https://res.cloudinary.com/deabexp8e/image/upload/v1746101881/ITEK%20Front/ROPA%20HOMBRE/lino/l3tdiuop20xmygs8nmdf.jpg', 'https://res.cloudinary.com/deabexp8e/image/upload/v1746101883/ITEK%20Front/ROPA%20HOMBRE/lino/cm1zehizjy0mbageud79.jpg', 'https://res.cloudinary.com/deabexp8e/image/upload/v1746101884/ITEK%20Front/ROPA%20HOMBRE/lino/hbstvfwuu6ecarwzptyl.jpg', 'Negro', "hombre"),
( 'PANTALÓN RELAXED FIT ALGODÓN - lino' , 'lino' ,'1437/450/800','100% lino' ,'Los lavados a baja temperatura y los centrifugados delicados son más suaves con las prendas y ayudan a proteger el color, la forma y la estructura del tejido. Además, reducen la cantidad de energía utilizada en los procesos de cuidado.' , 'Pantalón relaxed fit confeccionado en tejido con mezcla de algodón y 14% de lino. Cintura elástica ajustable con cordón. Bolsillos frontales y detalle de bolsillos traseros.', 29.95, 1200, 'https://res.cloudinary.com/deabexp8e/image/upload/v1746101881/ITEK%20Front/ROPA%20HOMBRE/lino/l3tdiuop20xmygs8nmdf.jpg', 'https://res.cloudinary.com/deabexp8e/image/upload/v1746101883/ITEK%20Front/ROPA%20HOMBRE/lino/cm1zehizjy0mbageud79.jpg', 'https://res.cloudinary.com/deabexp8e/image/upload/v1746101884/ITEK%20Front/ROPA%20HOMBRE/lino/hbstvfwuu6ecarwzptyl.jpg', 'Negro', "hombre"),
( 'PANTALÓN RELAXED FIT ALGODÓN - lino' , 'lino' ,'1437/450/800','100% lino' ,'Los lavados a baja temperatura y los centrifugados delicados son más suaves con las prendas y ayudan a proteger el color, la forma y la estructura del tejido. Además, reducen la cantidad de energía utilizada en los procesos de cuidado.' , 'Pantalón relaxed fit confeccionado en tejido con mezcla de algodón y 14% de lino. Cintura elástica ajustable con cordón. Bolsillos frontales y detalle de bolsillos traseros.', 29.95, 1200, 'https://res.cloudinary.com/deabexp8e/image/upload/v1746101881/ITEK%20Front/ROPA%20HOMBRE/lino/l3tdiuop20xmygs8nmdf.jpg', 'https://res.cloudinary.com/deabexp8e/image/upload/v1746101883/ITEK%20Front/ROPA%20HOMBRE/lino/cm1zehizjy0mbageud79.jpg', 'https://res.cloudinary.com/deabexp8e/image/upload/v1746101884/ITEK%20Front/ROPA%20HOMBRE/lino/hbstvfwuu6ecarwzptyl.jpg', 'Negro', "hombre");

-- tallas de la primera prenda
INSERT INTO product_tallas (product_id, talla)
VALUES
  (1, 'S'),
  (1, 'M'),
  (1, 'L'),
  (2, 'S'),
  (2, 'L'),
  (2, 'XL');

-- Insertar 2 carritos de golpe (para usuario 1 y 2)
INSERT INTO carts (usuario_id) 
VALUES (1), (2);


